name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'workday-task-board/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'workday-task-board/package-lock.json'

      - name: Install dependencies
        working-directory: workday-task-board
        run: npm ci

      - name: Set BASE_PATH for GitHub Pages
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          if [[ "$REPO_NAME" == *.github.io ]]; then
            echo "BASE_PATH=/" >> $GITHUB_ENV
          else
            echo "BASE_PATH=/$REPO_NAME/" >> $GITHUB_ENV
          fi

      - name: Build
        working-directory: workday-task-board
        run: npm run build
        env:
          BASE_PATH: ${{ env.BASE_PATH }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: workday-task-board/dist

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
